Added-from-trials-2
chawkimbarki/Microverse-trials-review pull request #1
Opened 2022-12-16 08:21 UTC by chawkimbarki

# files for review :

- `index.html`
- `style.css`

!!!_The other files are included by default, do not review them_!!!

2022-12-16 08:37 UTC, chawkimbarki commented
Hello @chawkimbarki 👋 

Great job so far 👍, I really liked how you used HTML semantic elements and gave meaningful names to classes and ids, the website overall looks stunning and almost identical to the Design 🌟 
However, it is still missing some small details to become even better, you are almost there 🤓  

# Changes Required :
- Install linter for HTML & CSS and fix all linter errors.
- Add a descriptive readme file, I recommend using this template and modifying it to fit your project details and requirements: https://github.com/microverseinc/readme-template.

# GOOD LUCK 🍀

2022-12-16 08:54 UTC, jerryowusu requested changes
Hi @chawkimbarki , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![so-close](https://user-images.githubusercontent.com/65233860/208060445-3337cb2b-80b7-4211-b8d4-a0b22d6a1bea.gif)


## Highlights
Great effort in giving the review :+1: 
Nice use of emojis/icons :grinning: 

## Required Changes ♻️

- [x] Kindly consider using the [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) at least once to leave review comments
- [ ] Kindly ensure that your comments are given in a respectful and polite, manner as suggestions instead of commands. :wink: This will be easier to understand and applied. 
- [ ] Also, please remember to give a reason for each requested change to help the student understand and make it easy for implementation. :+1: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 12:24 UTC, chawkimbarki reviewed
# You Are Almost There 🤓

- Read the comments and try to apply them with care and love ❤️
- after that, you can request another review to move to the next level 😎

2023-01-18 12:24 UTC, chawkimbarki commented on css/style.css
> +}
I recommend that you use a more precise selector or class to center a text because you don't know about the future were you might want a text to be aligned to the left.
so for example try using `h1` instead of `*`.


```suggestion
*{
	margin: 0;
	padding: 0;
	font-family: sans-serif;
    box-sizing: border-box;
}
h1 {
    text-align: center;
}
```

2023-01-18 12:24 UTC, chawkimbarki commented on css/style.css
> +
- It looks like you did pass all the tests

![image](https://user-images.githubusercontent.com/77485409/213169328-dfa19432-2245-4754-96fe-8fa08da0009a.png)

- if you open the test you'll see that you need to add some styles to the `<img>` element.

![image](https://user-images.githubusercontent.com/77485409/213169692-78e43817-d508-4230-a927-e0a293ee6b1a.png)

2023-01-18 12:40 UTC, jerryowusu approved these changes
Hi @chawkimbarki , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![chelsea-mason-approve](https://user-images.githubusercontent.com/65233860/213173905-ca85b144-b9d6-4ea8-980c-b9695e61fcd0.gif)


## Highlights
Used GitHub review feature :heavy_check_mark: 
Gave at least 2 review comments :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 12:42 UTC, merged